import type { Metadata } from "next";
import "./globals.css";
import { Inter as FontSans } from "next/font/google"
import { cn } from "@/lib/utils"
import { Toaster } from "@/components/ui/toaster";
import Header from "@/components/Header/Header";
import Navbar from "@/components/Navbar/Navbar";

 
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Envio email",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body 
         className={cn(
          "h-screen bg-slate-100 font-sans antialiased",
          fontSans.variable
        )}
      >
        <Header>
          <Navbar />
        </Header>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
