version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: envio_emails
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./database:/var/lib/mysql

  fontend:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app/frontend

  backend:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.backend
    ports:
      - 3333:3333
    volumes:
      - ./backend:/app/backend
    env_file:
      - ./backend/.env
    depends_on:
      - mysql